[tools]
# General
"aqua:atuinsh/atuin" = "latest"
bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ripgrep = "latest"
zoxide = "latest"

# Shell prompts
"aqua:JanDeDobbeleer/oh-my-posh" = "latest"
starship = "latest"

# Editors
neovim = "latest"
yazi = "latest"

# Languages
node = "lts"
go = "latest"
python = "latest"

# Structured parsing
fx = "latest"
jless = "latest"
jmespath = "latest"
jq = "latest"
jqp = "latest"
yq = "latest"

# Git
github-cli = "latest"
glab = "latest"
lazygit = "latest"

# API testing
hurl = "latest"
xh = "latest"

# Python
ruff = "latest"
uv = "latest"

# Lua
stylua = "latest"

# Shell
shellcheck = "latest"
shfmt = "latest"

# YAML
yamllint = "latest"

# HTML/XML
"npm:prettier" = "latest"

# Kubernetes
k9s = "latest"
kubectx = "latest"
kubens = "latest"

# Docker
nerdctl = "latest"
hadolint = "latest"

# Cloud
aws-cli = "latest"
terraform = "latest"

# Language servers
# TODO: Add language servers

# BUG: The latest version of tmux isn't able to compile correctly through asdf
# tmux = "latest"

