[tools]
bat = "latest"
broot = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
glow = "latest"
jless = "latest"
jq = "latest"
jqp = "latest"
just = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
ripgrep = "latest"
starship = "latest"
xh = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"

[plugins]
broot = 'https://github.com/cmur2/asdf-broot'
