[tools]

# Language Servers
lua-language-server = "latest"
marksman = "latest"
terraform-ls = "latest"
"npm:@ansible/ansible-language-server" = "latest"
"npm:basedpyright" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"go:golang.org/x/tools/gopls" = "latest"

